[main_page]
path = "Main.py"
name = "Main"

[student]
    [student.create_journal]
    path = "pages/1_Create_journal.py"
    name = "Create Journal"

    [student.view_past_journal]
    path = "pages/2_View_past_journals.py"
    name = "View past journals"

    [student.view_journal]
    path = "pages/6_View_journal.py"
    name = "View journal"

[teacher]
    [teacher.dashboard]
    path = "pages/3_Dashboard_summary.py"
    name = "Dashboard Summary"

    [teacher.classes]
    path = "pages/4_Teaching_classes.py"
    name = "Teaching Classes"

    [teacher.view_journal]
    path = "pages/5_View_student_journal.py"
    path_name = "View student journal"

    
[accessed_denied]
path = "pages/7_Access_Denied.py"
name = "Access denied"

[logout]
path = "pages/8_Logout.py"
name = "Logout"