[login_path_name]
path = "Login.py"
name = "Login"

[student]
    [student.create_journal]
    path = "pages/1_Create_journal.py"
    name = "Create Journal"

    [student.view_past_journal]
    path = "pages/2_View_past_journals.py"
    name = "View past journals"

[teacher]
    [teacher.dashboard]
    path = "pages/3_Dashboard_summary.py"
    name = "Dashboard Summary"

    [teacher.classes]
    path = "pages/4_Dashboard_summary.py"
    name = "Teaching Classes"

    [teacher.view_journal]
    path = "pages/5_View_student_journal.py"
    path_name = "View student journal"

[accessed_denied]
path = "pages/6_Access_Denied.py"
name = "Access denied"