[main_page]
path = "Main.py"
name = "Main"

[student]
    [student.create_journal]
    path = "pages/1_Create_journal.py"
    name = "Create journal"

    [student.view_past_journal]
    path = "pages/2_View_past_journals.py"
    name = "View past journals"

    [student.view_journal]
    path = "pages/6_View_journal.py"
    name = "View journal"

    [student.about_empathjot]
    path = "pages/10_About_Empathjot.py"
    name = "About EmpathJot"

[teacher]
    [teacher.dashboard]
    path = "pages/3_Dashboard_summary.py"
    name = "Dashboard summary"

    [teacher.classes]
    path = "pages/4_Teaching_classes.py"
    name = "Teaching classes"

    [teacher.view_journal]
    path = "pages/5_View_student_journal.py"
    path_name = "View student journal"

    
[accessed_denied]
path = "pages/7_Access_denied.py"
name = "Access denied"

[logout]
path = "pages/11_Logout.py"
name = "Logout"

[privacy_policy]
path = "pages/8_Privacy_policy.py"
name = "Privacy policy"

[data_protection]
path = "pages/9_Data_protection.py"
name = "Data protection"